//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowYourRep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representative
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Representative()
        {
            this.Votes = new HashSet<Vote>();
        }
    
        public int RepID { get; set; }
        public string RepName { get; set; }
        public string Gender { get; set; }
        public string Office { get; set; }
        public string Education { get; set; }
        public string Experience { get; set; }
        public int DistrictID { get; set; }
        public int AffiliationID { get; set; }
    
        public virtual Affiliation Affiliation { get; set; }
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
