//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowYourRep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int VoteID { get; set; }
        public int PolicyID { get; set; }
        public int RepID { get; set; }
    
        public virtual Policy Policy { get; set; }
        public virtual Representative Representative { get; set; }
    }
}
